"""add photo_name and photo_type fields for table Hero

Revision ID: 3a33dc9c4537
Revises: 946c5f8363b2
Create Date: 2025-03-25 22:01:40.500316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a33dc9c4537'
down_revision: Union[str, None] = '946c5f8363b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('photo_name', sa.String(), nullable=True), schema='open_content')
    op.add_column('hero', sa.Column('photo_type', sa.String(), nullable=True), schema='open_content')
    op.alter_column('hero', 'birth_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               schema='open_content')
    op.alter_column('hero', 'death_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               schema='open_content')
    op.alter_column('hero', 'enlistment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               schema='open_content')
    op.alter_column('hero', 'discharge_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               schema='open_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hero', 'discharge_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='open_content')
    op.alter_column('hero', 'enlistment_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='open_content')
    op.alter_column('hero', 'death_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='open_content')
    op.alter_column('hero', 'birth_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='open_content')
    op.drop_column('hero', 'photo_type', schema='open_content')
    op.drop_column('hero', 'photo_name', schema='open_content')
    # ### end Alembic commands ###
