"""create db structure

Revision ID: 946c5f8363b2
Revises: 
Create Date: 2025-03-25 20:25:03.427136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '946c5f8363b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('military_rank',
    sa.Column('military_rank_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('military_rank_id'),
    schema='open_content'
    )
    op.create_index(op.f('ix_open_content_military_rank_title'), 'military_rank', ['title'], unique=False, schema='open_content')
    op.create_table('war',
    sa.Column('war_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('war_id'),
    schema='open_content'
    )
    op.create_index(op.f('ix_open_content_war_title'), 'war', ['title'], unique=False, schema='open_content')
    op.create_table('hero',
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('death_date', sa.DateTime(), nullable=True),
    sa.Column('birth_place', sa.String(), nullable=True),
    sa.Column('war_id', sa.Integer(), nullable=False),
    sa.Column('military_rank_id', sa.Integer(), nullable=True),
    sa.Column('military_specialty', sa.String(), nullable=True),
    sa.Column('enlistment_date', sa.DateTime(), nullable=True),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('additional_information', sa.String(), nullable=True),
    sa.Column('moderation_status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='moderationstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['military_rank_id'], ['open_content.military_rank.military_rank_id'], ),
    sa.ForeignKeyConstraint(['war_id'], ['open_content.war.war_id'], ),
    sa.PrimaryKeyConstraint('hero_id'),
    schema='open_content'
    )
    op.create_index(op.f('ix_open_content_hero_birth_date'), 'hero', ['birth_date'], unique=False, schema='open_content')
    op.create_index(op.f('ix_open_content_hero_death_date'), 'hero', ['death_date'], unique=False, schema='open_content')
    op.create_index(op.f('ix_open_content_hero_military_rank_id'), 'hero', ['military_rank_id'], unique=False, schema='open_content')
    op.create_index(op.f('ix_open_content_hero_surname'), 'hero', ['surname'], unique=False, schema='open_content')
    op.create_index(op.f('ix_open_content_hero_war_id'), 'hero', ['war_id'], unique=False, schema='open_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_open_content_hero_war_id'), table_name='hero', schema='open_content')
    op.drop_index(op.f('ix_open_content_hero_surname'), table_name='hero', schema='open_content')
    op.drop_index(op.f('ix_open_content_hero_military_rank_id'), table_name='hero', schema='open_content')
    op.drop_index(op.f('ix_open_content_hero_death_date'), table_name='hero', schema='open_content')
    op.drop_index(op.f('ix_open_content_hero_birth_date'), table_name='hero', schema='open_content')
    op.drop_table('hero', schema='open_content')
    op.drop_index(op.f('ix_open_content_war_title'), table_name='war', schema='open_content')
    op.drop_table('war', schema='open_content')
    op.drop_index(op.f('ix_open_content_military_rank_title'), table_name='military_rank', schema='open_content')
    op.drop_table('military_rank', schema='open_content')
    # ### end Alembic commands ###
